server:
  port: 9411
spring:
  application:
    name: spring-boot-zipkin-server
  # 当前服务不使用 sleuth
  sleuth:
    enabled: false

management:
  metrics:
    web:
      server:
        # 避免访问 zipkin 页面报 java.lang.IllegalArgumentException
        auto-time-requests: false

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
  instance:
    # 是否注册 IP 到 eureka server，如不指定或设为 false，那就会注册主机名到 eureka server
    prefer-ip-address: true